//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface AppExitedEvent : EventRecord {
	int appExitedAccessibilityFeaturesActive;
}

+ (void)logWithAppExitedAccessibilityFeaturesActive:(int)appExitedAccessibilityFeaturesActive;

@property (nonatomic, assign) int appExitedAccessibilityFeaturesActive;

@end
