//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface AppLaunchedEvent : EventRecord {
	int accessibilityFeaturesActiveOnLaunch;
}

+ (void)logWithAccessibilityFeaturesActiveOnLaunch:(int)accessibilityFeaturesActiveOnLaunch;

@property (nonatomic, assign) int accessibilityFeaturesActiveOnLaunch;

@end
