//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface ButtonPressedEvent : EventRecord {
	NSString* buttonPressedButtonId;
	NSString* buttonPressedButtonTitle;
}

+ (void)logWithButtonPressedButtonId:(NSString*)buttonPressedButtonId withButtonPressedButtonTitle:(NSString*)buttonPressedButtonTitle;

@property (nonatomic, retain) NSString* buttonPressedButtonId;
@property (nonatomic, retain) NSString* buttonPressedButtonTitle;

@end
