//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface ContentScreenViewedEvent : EventRecord {
	long long contentScreenTimestampStart;
	long long contentScreenTimestampDismissal;
	NSString* contentScreenName;
	NSString* contentScreenDisplayName;
	int contentScreenType;
	NSString* contentScreenId;
}

+ (void)logWithContentScreenTimestampStart:(long long)contentScreenTimestampStart withContentScreenTimestampDismissal:(long long)contentScreenTimestampDismissal withContentScreenName:(NSString*)contentScreenName withContentScreenDisplayName:(NSString*)contentScreenDisplayName withContentScreenType:(int)contentScreenType withContentScreenId:(NSString*)contentScreenId;

@property (nonatomic, assign) long long contentScreenTimestampStart;
@property (nonatomic, assign) long long contentScreenTimestampDismissal;
@property (nonatomic, retain) NSString* contentScreenName;
@property (nonatomic, retain) NSString* contentScreenDisplayName;
@property (nonatomic, assign) int contentScreenType;
@property (nonatomic, retain) NSString* contentScreenId;

@end
