//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface DailyAssessmentEvent : EventRecord {
	int overallMood;
	int sleepWell;
	int howMuchAnger;
	int conflictWithOthers;
	int needForCoping;
	NSString* copingSituations;
	int overallCoping;
	int qualityOfGettingThingsDone;
	NSMutableArray* copingToolsUsed;
	int copingSupport;
	int takePrescribedMedications;
	int medicationSideEffects;
	int drinkAlcohol;
	int howMuchAlcohol;
	int takeNonPrescribedDrug;
}

+ (void)logWithOverallMood:(int)overallMood withSleepWell:(int)sleepWell withHowMuchAnger:(int)howMuchAnger withConflictWithOthers:(int)conflictWithOthers withNeedForCoping:(int)needForCoping withCopingSituations:(NSString*)copingSituations withOverallCoping:(int)overallCoping withQualityOfGettingThingsDone:(int)qualityOfGettingThingsDone withCopingToolsUsed:(NSArray*)copingToolsUsed withCopingSupport:(int)copingSupport withTakePrescribedMedications:(int)takePrescribedMedications withMedicationSideEffects:(int)medicationSideEffects withDrinkAlcohol:(int)drinkAlcohol withHowMuchAlcohol:(int)howMuchAlcohol withTakeNonPrescribedDrug:(int)takeNonPrescribedDrug;

@property (nonatomic, assign) int overallMood;
@property (nonatomic, assign) int sleepWell;
@property (nonatomic, assign) int howMuchAnger;
@property (nonatomic, assign) int conflictWithOthers;
@property (nonatomic, assign) int needForCoping;
@property (nonatomic, retain) NSString* copingSituations;
@property (nonatomic, assign) int overallCoping;
@property (nonatomic, assign) int qualityOfGettingThingsDone;
@property (nonatomic, retain) NSMutableArray* copingToolsUsed;
@property (nonatomic, assign) int copingSupport;
@property (nonatomic, assign) int takePrescribedMedications;
@property (nonatomic, assign) int medicationSideEffects;
@property (nonatomic, assign) int drinkAlcohol;
@property (nonatomic, assign) int howMuchAlcohol;
@property (nonatomic, assign) int takeNonPrescribedDrug;

@end
