//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface FunctioningAssessmentEvent : EventRecord {
	int howDifficult;
}

+ (void)logWithHowDifficult:(int)howDifficult;

@property (nonatomic, assign) int howDifficult;

@end
