//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PclAssessmentEvent : EventRecord {
	int pcl1;
	int pcl2;
	int pcl3;
	int pcl4;
	int pcl5;
	int pcl6;
	int pcl7;
	int pcl8;
	int pcl9;
	int pcl10;
	int pcl11;
	int pcl12;
	int pcl13;
	int pcl14;
	int pcl15;
	int pcl16;
	int pcl17;
}

+ (void)logWithPcl1:(int)pcl1 withPcl2:(int)pcl2 withPcl3:(int)pcl3 withPcl4:(int)pcl4 withPcl5:(int)pcl5 withPcl6:(int)pcl6 withPcl7:(int)pcl7 withPcl8:(int)pcl8 withPcl9:(int)pcl9 withPcl10:(int)pcl10 withPcl11:(int)pcl11 withPcl12:(int)pcl12 withPcl13:(int)pcl13 withPcl14:(int)pcl14 withPcl15:(int)pcl15 withPcl16:(int)pcl16 withPcl17:(int)pcl17;

@property (nonatomic, assign) int pcl1;
@property (nonatomic, assign) int pcl2;
@property (nonatomic, assign) int pcl3;
@property (nonatomic, assign) int pcl4;
@property (nonatomic, assign) int pcl5;
@property (nonatomic, assign) int pcl6;
@property (nonatomic, assign) int pcl7;
@property (nonatomic, assign) int pcl8;
@property (nonatomic, assign) int pcl9;
@property (nonatomic, assign) int pcl10;
@property (nonatomic, assign) int pcl11;
@property (nonatomic, assign) int pcl12;
@property (nonatomic, assign) int pcl13;
@property (nonatomic, assign) int pcl14;
@property (nonatomic, assign) int pcl15;
@property (nonatomic, assign) int pcl16;
@property (nonatomic, assign) int pcl17;

@end
