//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PclAssessmentCompletedEvent : EventRecord {
	long long pclAssessmentCompletedFinalScore;
	int pclAssessmentCompleted;
}

+ (void)logWithPclAssessmentCompletedFinalScore:(long long)pclAssessmentCompletedFinalScore withPclAssessmentCompleted:(int)pclAssessmentCompleted;

@property (nonatomic, assign) long long pclAssessmentCompletedFinalScore;
@property (nonatomic, assign) int pclAssessmentCompleted;

@end
