//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PclAssessmentStartedEvent : EventRecord {
	long long pclAssessmentStarted;
}

+ (void)logWithPclAssessmentStarted:(long long)pclAssessmentStarted;

@property (nonatomic, assign) long long pclAssessmentStarted;

@end
