//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PclAssessmentAbortedEvent : EventRecord {
	long long pclAssessmentAbortedTimestamp;
}

+ (void)logWithPclAssessmentAbortedTimestamp:(long long)pclAssessmentAbortedTimestamp;

@property (nonatomic, assign) long long pclAssessmentAbortedTimestamp;

@end
