//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PclReminderScheduledEvent : EventRecord {
	long long pclReminderScheduledTimestamp;
}

+ (void)logWithPclReminderScheduledTimestamp:(long long)pclReminderScheduledTimestamp;

@property (nonatomic, assign) long long pclReminderScheduledTimestamp;

@end
