//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface Phq9SurveyEvent : EventRecord {
	int phq91;
	int phq92;
	int phq93;
	int phq94;
	int phq95;
	int phq96;
	int phq97;
	int phq98;
	int phq99;
}

+ (void)logWithPhq91:(int)phq91 withPhq92:(int)phq92 withPhq93:(int)phq93 withPhq94:(int)phq94 withPhq95:(int)phq95 withPhq96:(int)phq96 withPhq97:(int)phq97 withPhq98:(int)phq98 withPhq99:(int)phq99;

@property (nonatomic, assign) int phq91;
@property (nonatomic, assign) int phq92;
@property (nonatomic, assign) int phq93;
@property (nonatomic, assign) int phq94;
@property (nonatomic, assign) int phq95;
@property (nonatomic, assign) int phq96;
@property (nonatomic, assign) int phq97;
@property (nonatomic, assign) int phq98;
@property (nonatomic, assign) int phq99;

@end
