//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PostExerciseSudsEvent : EventRecord {
	long long initialSudsScore;
	long long postExerciseSudsScore;
}

+ (void)logWithInitialSudsScore:(long long)initialSudsScore withPostExerciseSudsScore:(long long)postExerciseSudsScore;

@property (nonatomic, assign) long long initialSudsScore;
@property (nonatomic, assign) long long postExerciseSudsScore;

@end
