//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface PreExerciseSudsEvent : EventRecord {
	long long preExerciseSudsScore;
}

+ (void)logWithPreExerciseSudsScore:(long long)preExerciseSudsScore;

@property (nonatomic, assign) long long preExerciseSudsScore;

@end
