//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface TimePerScreenEvent : EventRecord {
	NSString* screenId;
	long long screenStartTime;
	long long timeSpentOnScreen;
}

+ (void)logWithScreenId:(NSString*)screenId withScreenStartTime:(long long)screenStartTime withTimeSpentOnScreen:(long long)timeSpentOnScreen;

@property (nonatomic, retain) NSString* screenId;
@property (nonatomic, assign) long long screenStartTime;
@property (nonatomic, assign) long long timeSpentOnScreen;

@end
