//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface TimeElapsedBetweenPCLAssessmentsEvent : EventRecord {
	long long timeElapsedBetweenPCLAssessments;
}

+ (void)logWithTimeElapsedBetweenPCLAssessments:(long long)timeElapsedBetweenPCLAssessments;

@property (nonatomic, assign) long long timeElapsedBetweenPCLAssessments;

@end
