//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface ToolAbortedEvent : EventRecord {
	NSString* toolId;
	NSString* toolName;
}

+ (void)logWithToolId:(NSString*)toolId withToolName:(NSString*)toolName;

@property (nonatomic, retain) NSString* toolId;
@property (nonatomic, retain) NSString* toolName;

@end
