//
//  Autogenerated... do not edit
//

#import "EventLog.h"
#import "EventRecord.h"

@interface TotalTimeOnAppEvent : EventRecord {
	long long totalTimeOnApp;
}

+ (void)logWithTotalTimeOnApp:(long long)totalTimeOnApp;

@property (nonatomic, assign) long long totalTimeOnApp;

@end
